language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
before install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run test:single
after_success:
  - npm run semantic-release